import Header from './Header'
import HeaderB from './HeaderB'
import Head from 'next/head'
import Footer from '../components/Footer'
import Provider from '../utils/Context'

export default function Layout({children}) {
  return (
    <Provider>
      <div className='min-h-[100vh]'>
        <Head>
          <title>Pizza App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          <Header />
          <HeaderB />
          {children}
          <Footer />
      </div>
    </Provider>
  )
}
