import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pizza App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className=''>Hello next</h1>
    </div>
  )
}
